### ISSUE TITLE
Multiple Set-Cookie headers in curl response overwrite each other

### ISSUE THREAD

**Issue by alanhartless** [joomla-framework/http#27]
Not sure if this is something that should be fixed be or is willing to be fixed - but finding a scenario where a curl response could have multiple `Set-Cookie` headers. But because https://github.com/joomla-framework/http/blob/master/src/Transport/Curl.php#L279 merges the headers into an associative array, only the last header is made available to the calling script with no way to access the original headers. 

To reproduce, create a simple script that set's several cookies with `setcookie()`. Then a second script using this  package to post to it and examine the `$response->headers`. Only the last `Set-Cookie` header will be available. 

As a work around - will look at using a curl cookie jar but was hoping for something "in memory" rather than writing cookies to a file.

**Comment by mbabker** [comment]
So here's the "stuck between a rock and a hard place" answer.  Changing this on the master (v1) branch probably constitutes a B/C break (quickest solution would be to convert the header to use an array instead of a string to allow multiple values).  The 2.0 branch is refactored to use Zend Diactoros to return PSR-7 compatible response objects which by design uses an array of values for each named header.

If you can, run off the 2.0 branch and you'll be fine going forward.  But this is most likely something that can't be addressed in the stable 1.x code.

**Comment by alanhartless** [comment]
Hey! Long time no talk :-) Hope all is well. 

Yea, I agree - it would be a BC break. So I'll look at 2.0 to see if it's a possibility without causing BC issues with the implementation. 

Thanks!
